  const CREDENTIAL_TYPES = {
    certification: 'Professional certification',
    certification_history: 'Certification history',
    training: 'Formal training',
    course: 'Course completion',
    awareness: 'Corporate awareness'
  };

  const CREDENTIALS = [
    {
      id: 'psm1',
      name: 'Professional Scrum Master I',
      shortTitle: 'PSM I',
      issuer: 'Scrum.org',
      year: '2026',
      issuedLabel: '2026',
      type: 'certification',
      status: 'valid',
      statusLabel: 'Valid',
      relevance: 'current',
      featured: true,
      priority: 1,
      file: './Certification/Professional Scrum Master I.pdf',
      summary: 'Validates Scrum-framework knowledge — empiricism, accountabilities, events and artifacts.',
      supports: 'Scrum framework knowledge for delivery visibility, requirements and validation work.',
      lineage: 'scrum'
    },
    {
      id: 'aws-clf',
      name: 'AWS Certified Cloud Practitioner (CLF-C01)',
      shortTitle: 'AWS CLF-C01',
      issuer: 'Amazon Web Services',
      year: '2023',
      issuedLabel: '2023',
      expiresLabel: 'Apr 2026',
      type: 'certification_history',
      status: 'expired',
      statusLabel: 'Expired Apr 2026',
      score: '754 / 1000',
      relevance: 'foundational',
      featured: false,
      priority: 2,
      file: './Certification/AWS Certified Cloud Practitioner certificate.pdf',
      summary: 'Historical AWS foundational certification demonstrating prior formal knowledge of core cloud concepts.',
      supports: 'Cloud concepts, shared responsibility and core service awareness.',
      lineage: 'cloud'
    },
    {
      id: 'java-fs',
      name: 'Certificate Program in Java Full Stack',
      shortTitle: 'Java Full Stack',
      issuer: 'StackRoute / Wipro Velocity',
      year: 'Jul 2022',
      issuedLabel: 'Jul 2022',
      type: 'training',
      status: 'completed',
      statusLabel: 'Completed',
      relevance: 'foundational',
      featured: false,
      priority: 3,
      file: './Certification/Certificate Program in Java Full Stack.pdf',
      summary: 'Formal technical training completed through Wipro’s learning program.',
      supports: 'Java, application architecture, databases, APIs and software-delivery concepts.',
      lineage: 'software'
    },
    {
      id: 'ibm-sql',
      name: 'Databases and SQL for Data Science with Python',
      shortTitle: 'IBM SQL',
      issuer: 'IBM / Coursera',
      year: 'Nov 2025',
      issuedLabel: 'Nov 2025',
      type: 'course',
      status: 'completed',
      statusLabel: 'Completed',
      relevance: 'foundational',
      featured: false,
      priority: 4,
      file: './Certification/Coursera DB3FW2MT3J9T.pdf',
      summary: 'Course foundation in relational databases and SQL concepts.',
      supports: 'SQL / data foundation — practical SQL depth is currently being strengthened.',
      lineage: 'software'
    },
    {
      id: 'aws-essentials',
      name: 'AWS Cloud Practitioner Essentials',
      shortTitle: 'AWS Essentials',
      issuer: 'AWS Training',
      year: 'Nov 2022',
      issuedLabel: 'Nov 2022',
      type: 'course',
      status: 'completed',
      statusLabel: 'Completed',
      relevance: 'foundational',
      featured: false,
      priority: 5,
      file: './Certification/AWS Training & Certification - Certificate of Completion.pdf',
      summary: 'Course completion supporting the later AWS Cloud Practitioner certification path.',
      supports: 'Introductory cloud concepts ahead of certification.',
      lineage: 'cloud'
    },
    {
      id: 'data-privacy',
      name: 'Data Privacy Awareness',
      shortTitle: 'Data Privacy',
      issuer: 'Wipro',
      year: 'Oct 2022',
      issuedLabel: 'Oct 2022',
      type: 'awareness',
      status: 'completed',
      statusLabel: 'Completed',
      relevance: 'supporting',
      featured: false,
      priority: 6,
      file: './Certification/Data Privacy Awareness Certificate.pdf',
      summary: 'Corporate awareness training on data privacy and compliance expectations.',
      supports: 'Enterprise privacy/compliance awareness — not specialist privacy expertise.',
      lineage: 'corporate'
    },
    {
      id: 'digital-marketing',
      name: 'Fundamentals of Digital Marketing',
      shortTitle: 'Digital Marketing',
      issuer: 'Google Digital Garage',
      year: 'Nov 2021',
      issuedLabel: 'Nov 2021',
      type: 'course',
      status: 'completed',
      statusLabel: 'Completed',
      relevance: 'earlier',
      featured: false,
      priority: 7,
      file: './Certification/The Fundamentals of Digital Marketing Certificate.pdf',
      summary: 'Earlier business / digital learning exploration.',
      supports: 'Foundational digital marketing concepts.',
      lineage: 'explore'
    },
    {
      id: 'robotics',
      name: 'Robotics: Aerial Robotics',
      shortTitle: 'Aerial Robotics',
      issuer: 'University of Pennsylvania / Coursera',
      year: 'Oct 2021',
      issuedLabel: 'Oct 2021',
      type: 'course',
      status: 'completed',
      statusLabel: 'Completed',
      relevance: 'earlier',
      featured: false,
      priority: 8,
      file: './Certification/Coursera 8K8XIRBAIJMV.pdf',
      summary: 'Earlier technical exploration outside current support/implementation focus.',
      supports: 'Technical curiosity and structured online learning.',
      lineage: 'explore'
    }
  ];

  const CREDENTIAL_TIMELINE = [
    { when: '2021', label: 'Exploration', detail: 'Aerial Robotics · Digital Marketing' },
    { when: '2022', label: 'Technical foundation', detail: 'Java Full Stack · AWS Essentials · Data Privacy' },
    { when: '2023', label: 'Cloud certification', detail: 'AWS Certified Cloud Practitioner (CLF-C01)' },
    { when: '2025', label: 'Data foundation', detail: 'IBM Databases and SQL course' },
    { when: '2026', label: 'Scrum credential', detail: 'Professional Scrum Master I — valid' },
    { when: 'Now', label: 'Practical depth', detail: 'SQL · APIs · ITSM · Linux · Networking', current: true }
  ];
